global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node_exporter'
    scrape_interval: 1s
    static_configs:
      - targets: ['10.10.1.3:9100']
        labels:
            instance: 'server1'
      - targets: ['10.10.1.4:9100']
        labels:
            instance: 'server2'
