version: '2.3'

services:
    node_exporter:
        image: prom/node-exporter
        command: --collector.textfile.directory=/run/prometheus
        pid: "host"
        volumes:
            - prometheus_data:/prometheus
            - prometheus_textfiles:/run/prometheus:ro
        ports:
            - 9100:9100
        networks:
            - default

    dcgm_exporter:
        image: nvidia/dcgm-exporter:1.4.3
        runtime: nvidia
        volumes:
            - prometheus_textfiles:/run/prometheus
        networks:
            - default

volumes:
    prometheus_textfiles:
        driver_opts:
            type: tmpfs
            device: tmpfs
    prometheus_data:
        driver: local
    grafana_data:
        driver: local

networks:
    default:
        driver: bridge
